### ISSUE TITLE
Strapi 5.1.0 with plugins version 2.0.0 - Cannot indexing the content

### ISSUE THREAD

**Issue by hoqkhanh** [wizbii/strapi-plugin-strapi-algolia#15]
We installed the plugins with plugins config:

'strapi-algolia': {
    enabled: true,
    config: {
      apiKey: env('ALGOLIA_ADMIN_KEY'),
      applicationId: env('ALGOLIA_APP_ID'),
      contentTypes: [
        { name: 'api::account-type.account-type' },
        { name: 'api::blog.blog' },
        { name: 'api::market-page.market-page' },
        { name: 'api::more-resource.more-resource' },
        { name: 'api::platform.platform' },
        { name: 'api::trading.trading' },
      ],
    },
  },
After that, we ran the indexing  button in the content management section:

<img width="1397" alt="Screenshot 2024-10-22 at 11 02 34" src="https://github.com/user-attachments/assets/25cdb88b-d443-4efb-bb48-c7c5fa95ecff">

But In the algolia, we don't see any index record 

<img width="1214" alt="Screenshot 2024-10-22 at 14 18 13" src="https://github.com/user-attachments/assets/39deaed1-ddfb-4c5a-90fb-ff22f149e1a8">

Also we checked the algolia API log, it just pushed the deleteObject to the algolia indexing API 
<img width="1018" alt="Screenshot 2024-10-22 at 11 02 22" src="https://github.com/user-attachments/assets/943444ee-9727-4b27-8cef-3450fd8d68c9">

Please advise us on our case.

**Comment by squelix** [comment]
I will look for thus bug

**Comment by hoqkhanh** [comment]
Thank you so much @squelix

**Comment by hoqkhanh** [comment]
Hi @squelix Sorry, Do you know when the PR approval for this issue will be?
